BASE_KEYPOINT_INITIAL_OFFSETS = {"ArmL": "0. 0. 0.",
                                 "ArmR": "0. 0. 0.",
                                 "ElbowL": "0. 0. 0.",
                                 "ElbowR": "0. 0. 0.",
                                 "HeadB": "0. -.025 .045",
                                 "HeadF": ".025 -.025 .045",
                                 "HeadL": "0. .025 .045",
                                 "HipL": "0. 0. 0.005",
                                 "HipR": "0. 0. 0.005",
                                 "KneeL": "0. 0. 0.",
                                 "KneeR": "0. 0. 0.",
                                 "Offset1": "0.015 .0155 -0.005",
                                 "Offset2": "-0.015 .015 -0.005",
                                 "ShinL": "0.015 0.01 0.0125",
                                 "ShinR": "0.015 -0.01 0.0125",
                                 "ShoulderL": "0. 0. 0.",
                                 "ShoulderR": "0. 0. 0.",
                                 "SpineF": "0. 0. 0.005",
                                 "SpineL": "0. 0. 0.005",
                                 "SpineM": "0. 0. 0.005"}
KEYPOINT_INITIAL_OFFSETS = {"ArmL": "0. 0. 0.",
                            "ArmR": "0. 0. 0.",
                            "ElbowL": "0. 0. 0.",
                            "ElbowR": "0. 0. 0.",
                            "HeadB": "0. -.025 .045",
                            "HeadF": ".025 -.025 .045",
                            "HeadL": "0. .025 .045",
                            "HipL": "0.03 0. 0.04",
                            "HipR": "0. 0. 0.005",
                            "KneeL": "0. 0. 0.03",
                            "KneeR": "0. 0. 0.",
                            "Offset1": "0.015 .0155 -0.005",
                            "Offset2": "-0.015 .015 -0.005",
                            "ShinL": "0.02 0. 0.015",
                            "ShinR": "0.015 -0.01 0.0125",
                            "ShoulderL": "0. 0. 0.",
                            "ShoulderR": "0. 0. 0.",
                            "SpineF": "0. 0. 0.005",
                            "SpineL": "0. 0. 0.005",
                            "SpineM": "0. 0. 0.005"}

COLORS = {"LEFT_LEG": "0 0 .3 1",
          "RIGHT_LEG": ".3 0 0 1",
          "LEFT_ARM": "0 0 .8 1",
          "RIGHT_ARM": ".8 0 0 1",
          "HEAD": ".8 .8 0 1",
          "SPINE": ".8 .8 .8 1"}

KEYPOINT_COLOR_PAIRS = {"ArmL": COLORS["LEFT_ARM"],
                        "ArmR": COLORS["RIGHT_ARM"],
                        "ElbowL": COLORS["LEFT_ARM"],
                        "ElbowR": COLORS["RIGHT_ARM"],
                        "HeadB": COLORS["HEAD"],
                        "HeadF": COLORS["HEAD"],
                        "HeadL": COLORS["HEAD"],
                        "HipL": COLORS["LEFT_LEG"],
                        "HipR": COLORS["RIGHT_LEG"],
                        "KneeL": COLORS["LEFT_LEG"],
                        "KneeR": COLORS["RIGHT_LEG"],
                        "Offset1": COLORS["SPINE"],
                        "Offset2": COLORS["SPINE"],
                        "ShinL": COLORS["LEFT_LEG"],
                        "ShinR": COLORS["RIGHT_LEG"],
                        "ShoulderL": COLORS["LEFT_ARM"],
                        "ShoulderR": COLORS["RIGHT_ARM"],
                        "SpineF": COLORS["SPINE"],
                        "SpineL": COLORS["SPINE"],
                        "SpineM": COLORS["SPINE"]}
